### ISSUE TITLE
TypeError: Couldn't find foreign struct converter for 'cairo.Context'

### ISSUE THREAD

**Issue by km4ack** [km4ack/pi-build#342]
This error is seen when running xgps. To get rid of the error,
sudo apt-get install -y python-gi-cairo

Thanks to Dave, KD7UM, for pointing this out!

**Comment by btombaugh** [comment]
in BAP 3.1.3, the xgps app wouldn’t launch, said missing module cairo

pi@raspberrypi:~ $ xgps
Traceback (most recent call last):
  File "/usr/bin/xgps", line 24, in <module>
    import cairo
ImportError: No module named cairo

fixed by:

sudo apt -y install gpsd-tools gpsd-clients python**3**-gps chrony python**3**-gi-cairo

pi@raspberrypi:~ $ sudo apt -y install gpsd gpsd-clients python-gps chrony python-gi-cairo
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package python-gps is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  gpsd-tools gpsd-clients

E: Package 'python-gps' has no installation candidate
E: Unable to locate package python-gi-cairo
pi@raspberrypi:~ $ sudo apt -y install gpsd-tools gpsd-clients python-gps chrony python-gi-cairo
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package python-gps is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  gpsd-tools gpsd-clients

E: Package 'python-gps' has no installation candidate
E: Unable to locate package python-gi-cairo
pi@raspberrypi:~ $ sudo apt -y install gpsd-tools gpsd-clients python3-gps chrony python-gi-cairo
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package python-gi-cairo
pi@raspberrypi:~ $ sudo apt -y install gpsd-tools gpsd-clients python3-gps chrony python3-gi-cairo
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
chrony is already the newest version (4.0-8).
gpsd-tools is already the newest version (3.22-4).
gpsd-tools set to manually installed.
python3-gi-cairo is already the newest version (3.38.0-2).
python3-gi-cairo set to manually installed.
The following NEW packages will be installed:
  gpsd-clients python3-gps
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 590 kB of archives.
After this operation, 2,219 kB of additional disk space will be used.
Get:1 http://mirror.pit.teraswitch.com/raspbian/raspbian bullseye/main armhf python3-gps armhf 3.22-4 [161 kB]
Get:2 http://mirror.pit.teraswitch.com/raspbian/raspbian bullseye/main armhf gpsd-clients armhf 3.22-4 [429 kB]
Fetched 590 kB in 1s (445 kB/s)       
Selecting previously unselected package python3-gps.
(Reading database ... 143916 files and directories currently installed.)
Preparing to unpack .../python3-gps_3.22-4_armhf.deb ...
Unpacking python3-gps (3.22-4) ...
Selecting previously unselected package gpsd-clients.
Preparing to unpack .../gpsd-clients_3.22-4_armhf.deb ...
Unpacking gpsd-clients (3.22-4) ...
Setting up python3-gps (3.22-4) ...
Setting up gpsd-clients (3.22-4) ...
Processing triggers for gnome-menus (3.36.0-1) ...
Processing triggers for libc-bin (2.31-13+rpt2+rpi1) ...
Processing triggers for man-db (2.9.4-2) ...
Processing triggers for mailcap (3.69) ...
Processing triggers for desktop-file-utils (0.26-1) ...
pi@raspberrypi:~ $ xgps
xgps: host localhost port 2947
